---
sudo: required
language: python
virtualenv:
  system_site_packages: true
services:
  - docker
cache:
  - pip
before_install:
  - sudo apt-get -qq update
install:
  - python --version
  - pip install ansible
  - pip install -r install.txt
script:
  - python --version
  - source .venv/bin/activate
  - molecule test
