---
os:
  - linux
  - osx
sudo: required
language: python
services:
  - docker
cache:
  - pip
before_install:
  - tests/travis_before_install.sh
install:
  - virtualenv --no-site-packages .venv
  - source .venv/bin/activate
  - pip install ansible==2.5.0
  - pip install -r install.txt
script:
  - tests/travis.sh
