---
- name: Install awscli and python libs
  dnf:
    name:
      - awscli
      - python2-botocore
      - python2-boto3
      - python3-botocore
      - python3-boto3
    state: present
  become: true
  tags: aws awscli
