---
- name: Install mariadb
  dnf:
    name:
      - mariadb
      - mariadb-server
    state: present
  become: true
  tags: mariadb mysql

- name: Start mariadb service
  systemd:
    name: mariadb
    enabled: true
    state: started
  become: true
  tags: mariadb mysql

- name: Set mariadb root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_password: "{{ mysql_old_root_password }}"
  ignore_errors: true
  tags: mariadb mysql
  when: mysql_root_password != mysql_old_root_password

- name: Create ~/.my.cnf
  template:
    src: templates/mariadb/.my.cnf.j2
    dest: "/home/{{ primary_user }}/.my.cnf"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  tags: mariadb mysql

- name: Configure mariadb/mysql server
  copy:
    src: files/mysql/local.cnf
    dest: /etc/my.cnf.d/local.cnf
  notify: mariadb
  become: true
  tags: mariadb mysql
