---
- name: Install mariadb
  dnf:
    name:
      - mariadb
      - mariadb-server
    state: present
  become: true
  tags: mariadb mysql

- name: Start mariadb service
  systemd:
    name: mariadb
    enabled: true
    state: started
  become: true
  tags: mariadb mysql

- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check
  tags: mariadb

- name: Mysql root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    state: present
  when: root_pwd_check.rc == 0
  tags: mariadb

- name: Create ~/.my.cnf
  template:
    src: templates/mariadb/.my.cnf.j2
    dest: "/home/{{ primary_user }}/.my.cnf"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  tags: mariadb mysql

- name: Configure mariadb/mysql server
  copy:
    src: files/mysql/local.cnf
    dest: /etc/my.cnf.d/local.cnf
  notify: mariadb
  become: true
  tags: mariadb mysql
