---
- name: Install Node.js
  dnf:
    name: nodejs
    state: present
  become: true
  tags: node

- name: Install npm packages
  npm:
    name: "{{ item }}"
    state: present
    global: true
  with_items:
    - gulp
    - grunt
    - yarn
  become: true
  tags: node
